name: rival
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Used for NumberFormat in profile.dart
  intl: ^0.16.1
  
  ## Firebase
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_crashlytics: ^0.2.1+1
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.1.1
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  firebase_ml_vision: ^0.9.7
  firebase_dynamic_links: ^0.6.0+2
  firebase_remote_config: ^0.4.0+2

  ## Extra
  readmore: ^1.0.0
  like_button: ^1.0.1
  timeago: ^2.0.26
  eyro_toast: ^0.1.0
  quick_actions: ^0.4.0+10
  vibration: ^1.4.0
  receive_sharing_intent: ^1.4.0+2
  cached_network_image: ^2.2.0+1
  full_screen_image: ^1.0.2
  flutter_native_image: ^0.0.5+2
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  flutter_blurhash: ^0.5.0
  linkify: ^2.1.0
  liquid_progress_indicator: ^0.3.2
  material_tag_editor: ^0.0.2
  carousel_slider: ^2.2.1
  liquid_pull_to_refresh: ^2.0.0
  animated_splash_screen: ^1.0.0+1
  expandable: ^4.1.4
  flutter_linkify: ^3.1.3
  flutter_parsed_text: ^1.2.4
  url_launcher: ^5.5.0
  octo_image: ^0.2.1
  smooth_page_indicator: ^0.2.0
  shimmer: ^1.1.1
  pagination_view: ^1.0.3+2
  scrollable_positioned_list: ^0.1.7
  geocoder: ^0.2.1
  location: ^3.2.4
  inview_notifier_list: ^1.0.0
  share: ^0.6.5+2
  visibility_detector: ^0.1.5
  animations: ^1.1.2
  native_state: ^1.1.1
  story_view: ^0.12.3
  file_picker: ^1.13.3
  mime: ^0.9.7
  flutter_colorpicker: ^0.3.4
  video_player: ^0.10.12+2
  dotted_border: ^1.0.6
  step_progress_indicator: ^0.2.4+7
  timer_count_down: ^1.0.4+1
  flutter_staggered_grid_view: ^0.3.2
  flutter_local_notifications: ^1.4.4+4
  app_settings: ^4.0.4
  flutter_svg: ^0.19.0
  flutter_slidable: ^0.5.7
  preload_page_view: ^0.1.4
  custom_navigation_bar: ^0.3.2
  page_transition: ^1.1.7+2
  cube_transition: ^1.0.2
  provider: ^4.3.2+2
  delayed_display: ^1.0.3
  supercharged: ^1.10.0
  image: ^2.1.18
  path_provider: ^1.6.18
  meta: ^1.1.6
  bitmap: ^0.0.6
  numberpicker: ^1.2.1
  image_gallery_saver: ^1.6.0
  permission_handler: ^5.0.1+1
  dio: ^3.0.10
  #device_preview: ^0.4.8
  image_editor: ^0.7.3
  extended_image: ^1.3.0
  flutter_credit_card: ^0.1.3
  #stripe_payment: ^1.0.9
  charts_flutter: ^0.9.0
  flutter_native_admob: ^2.1.0+3
  mask_text_input_formatter: ^1.1.0
  shared_preferences: ^0.5.12+4
  flutter_icons: ^1.1.0
  introduction_screen: ^1.0.9
  property_change_notifier: ^0.2.0
  screenshot: ^0.2.0
  auto_size_text: ^2.1.0
  responsive_flutter: ^0.0.4
  device_info: ^1.0.0
  polygon_clipper: ^1.0.2
  flutter_webrtc: ^0.5.8

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  image: assets/launch_background.png
  color: '#536dfe'

flutter:

  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/icon.png
    - assets/verified.svg
    - assets/intro/business/collaborate.svg
    - assets/intro/business/insights.svg
    - assets/intro/business/shop.svg
    - assets/intro/business/shopping.svg
    - assets/intro/creator/add_post.svg
    - assets/intro/creator/content.svg
    - assets/intro/creator/create.svg
    - assets/intro/creator/designer.svg
    - assets/intro/creator/discoverable.svg
    - assets/intro/creator/publish.svg
    - assets/intro/creator/spread_love.svg
    - assets/intro/creator/insights.svg

  fonts:
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf
    - family: DMSerifText
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro-Regular.ttf

## Source - https://medium.com/@amandeepkochhar/flutter-dart-the-class-cant-be-used-as-a-mixin-because-it-extends-a-class-other-than-object-a53eb5f214b0
## Used to allow multiple mixins
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true